=== SharpBlade/SharpBlade/CustomDictionary.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Just add stuff to this when more elements et.c are required. -->
<!-- This is purely to get rid of the INFO messages in the Error list about
     there not being a schema for CustomDictionary.xml -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Dictionary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Words">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Recognized">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="Word" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="DiscreteExceptions">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Term" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SharpBlade/SharpBlade/CustomDictionary.xml
<?xml version="1.0" encoding="utf-8"?>
<Dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CustomDictionary.xsd">
    <Words>
        <Recognized>
            <Word>callback</Word>
            <Word>Counterclockwise</Word>
            <Word>Razer</Word>
            <Word>RazerAPI</Word>
            <Word>Touchpoint</Word>
        </Recognized>
        <DiscreteExceptions>
            <Term>setup</Term>
        </DiscreteExceptions>
    </Words>
</Dictionary>
